### ISSUE TITLE
Start error !?

### ISSUE THREAD

**Issue by jonixfu** [theturtle32/WebSocket-Node#183]
D:\Projects\nodejs\WebSocket-Node-master\example\whiteboard>node whiteboard.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\Projects\nodejs\WebSocket-Node-master\lib\WebSocke
tServer.js:20:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by ibc** [comment]
Did you run `npm install` before?

**Comment by ibc** [comment]
Closing due lack of feedback. The solution is given anyhow.
