### ISSUE TITLE
Segmentation Fault on Node v0.12.0

### ISSUE THREAD

**Issue by aisouard** [theturtle32/WebSocket-Node#196]
I am trying to send some data with W3CWebSocket

```js
_ws.send('{"type":"announce", "hash":"12}');
```

And I get a SIGSEGV signal when I add more bytes :
```js
_ws.send('{"type":"announce", "hash":"123}');
```

Here is the output in gdb :
```raw
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff58d8e15 in BufferUtil::Mask(v8::FunctionCallbackInfo<v8::Value> const&) ()
   from /home/axel/work/node_modules/websocket/build/Release/bufferutil.node
(gdb) bt
#0  0x00007ffff58d8e15 in BufferUtil::Mask(v8::FunctionCallbackInfo<v8::Value> const&) ()
   from /home/axel/work/node_modules/websocket/build/Release/bufferutil.node
#1  0x00000000005f8ab7 in v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) ()
```

Here is the output with the -g3 flag :

```raw
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff58d8e15 in BufferUtil::Mask (args=...) at ../src/bufferutil.cc:98
98	    for (i = 0; i < len32; ++i) *(to + i) = *(from + i) ^ *mask;
(gdb) bt
#0  0x00007ffff58d8e15 in BufferUtil::Mask (args=...) at ../src/bufferutil.cc:98
#1  0x00000000005f8ab7 in v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) ()

(gdb) p i
$1 = <optimized out>
(gdb) p len32
$2 = 8
(gdb) p to
$3 = (unsigned int *) 0x103c710
(gdb) p from
$4 = (unsigned int *) 0x103c6ea
(gdb) p mask
$5 = (unsigned int *) 0x103c69c
(gdb) p *(to + i)
value has been optimized out
(gdb) p *(from + i)
value has been optimized out
```

It also occurs with the implementation in this package : https://github.com/websockets/ws/issues/451

Here is my npm ls output :

```raw
├─┬ websocket@1.0.18
│ ├─┬ debug@2.1.3
│ │ └── ms@0.7.0
│ ├── nan@1.0.0
│ └─┬ typedarray-to-buffer@3.0.1
│   └── is-typedarray@0.0.0
```

gcc -v output :

```raw
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: /build/gcc/src/gcc-4.9-20150304/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-cloog-backend=isl --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --disable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 4.9.2 20150304 (prerelease) (GCC)
```

It looks like someone is having the same issue in another websocket implementation : https://github.com/websockets/ws/issues/448

**Comment by aisouard** [comment]
Interesting stuff about BufferUtil there : https://github.com/websockets/bufferutil/issues/1

**Comment by theturtle32** [comment]
Is this an ongoing issue?
