### ISSUE TITLE
Latest install on OSX 10.10.5 errors

### ISSUE THREAD

**Issue by rgillan** [theturtle32/WebSocket-Node#219]
Trying to install via NPM on OSX 10.10.5 fails against Node 5.3.0.  node-gyp installed.  Latest XCode installed.  Run as root:

sh-3.2# npm install -g websocket

> websocket@1.0.22 install /usr/local/lib/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
/usr/local/lib
└─┬ websocket@1.0.22 
  ├─┬ debug@2.2.0 
  │ └── ms@0.7.1 
  ├── nan@2.0.9 
  ├─┬ typedarray-to-buffer@3.0.4 
  │ └── is-typedarray@1.0.0 
  └── yaeti@0.0.4 

sh-3.2# builderror.log:
cat /usr/local/lib/node_modules/websocket/builderror.log 
gyp WARN EACCES user "rob" does not have permission to access the dev dir "/var/root/.node-gyp/5.3.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/websocket/.node-gyp"

Not sure why node-gyp would be trying to use non root user during this process as all run as root.  Including the module in node.js code then fails:

sh-3.2# node /opt/nisient/lib/node/router.js 
module.js:328
    throw err;
    ^

Error: Cannot find module 'websocket'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/nisient/lib/node/router.js:30:19)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)

Any help or ideas very much appreciated.

Cheers
Rob

**Comment by rgillan** [comment]
OK, premature (sorry).

Had to manually run node-gyp configure build in the websocket directory, then fix the path:

export NODE_PATH=/usr/local/lib/node_modules

node now finds the websocket module

Cheers Rob
