### ISSUE TITLE
Node Install Error

### ISSUE THREAD

**Issue by thirdlastletter** [theturtle32/WebSocket-Node#239]
Hello,

I have installed the WebSocket Node in the Node.js folder as a module, but when I try to run a server script it can't find the module. 

C:\Users\...\Downloads\WebSocket-Node-master\WebSocket-Node-master>node ws_server.js
module.js:442
    throw err;
    ^

Error: Cannot find module 'C:Program Files
odejs
ode_moduleswebsocket'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\...\Downloads\WebSocket-Node-master\WebSocket-Node-master\ws_server.js:2:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

So I am trying to installe the websocketnode in the folder, where I am trying to run the script but I am getting the following error:

C:\Users\...\Downloads\WebSocket-Node-master\WebSocket-Node-master>npm install websocket
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "websocket"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ENOSELF

npm ERR! Refusing to install websocket as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\...\Downloads\WebSocket-Node-master\WebSocket-Node-master\npm-debug.log

Can someone help?
Thanks

**Comment by ibc** [comment]
> I have installed the WebSocket Node in the Node.js folder as a module

Why?

Have you seen the error you get?:

> "Refusing to install websocket as a dependency of itself"

Please, learn how Node.js and npm works.
