### ISSUE TITLE
RangeError: out of range index

### ISSUE THREAD

**Issue by seppevectera** [theturtle32/WebSocket-Node#253]
I am getting RangeErrors when emitting messages from a websocket server. This doesn't happen on every message, just now and then.
This only happens with Node >= 6.3
This is probably related to websockets/ws/issues/778

```
error: uncaughtException: out of range index date=Thu Sep 01 2016 13:38:12 GMT+0200 (CEST), pid=9150, uid=1000, gid=1000, cwd=/home/seppe/Documents/werk/vectera/code---/nodejs, execPath=/home/seppe/Documents/werk/vectera/code---/env/bin/node, version=v6.5.0, argv=[/home/seppe/Documents/werk/vectera/code---/env/bin/node, /home/seppe/Documents/werk/vectera/code---/nodejs/server], rss=51810304, heapTotal=27299840, heapUsed=20994872, loadavg=[3.53076171875, 3.06298828125, 2.3994140625], uptime=104237
RangeError: out of range index
    at RangeError (native)
    at fastCopy (/home/seppe/Documents/werk/vectera/code---/nodejs/node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:317:24)
    at Receiver.add (/home/seppe/Documents/werk/vectera/code---/nodejs/node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:78:3)
    at TLSSocket.firstHandler (/home/seppe/Documents/werk/vectera/code---/nodejs/node_modules/websocket-stream/node_modules/ws/lib/WebSocket.js:663:22)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:543:20)
```

**Comment by theturtle32** [comment]
The stack trace you've pasted is referencing code from the `ws` module, not from this module.
