### ISSUE TITLE
Error make maskKey (Node v10.0)

### ISSUE THREAD

**Issue by lokin-roman** [theturtle32/WebSocket-Node#315]
After updating Node.js (v10.0.0, Ubuntu 17.10 x64), an error occurred:

```
RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received -1314506580
    at checkInt (internal/buffer.js:35:11)
    at writeU_Int32BE (internal/buffer.js:625:3)
    at Buffer.writeUInt32BE (internal/buffer.js:638:10)
    at WebSocketFrame.toBuffer (PATH/node_modules/websocket/lib/WebSocketFrame.js:262:24)
```

The code that causes the error:
```
maskKey = nullMask ? 0 : (Math.random()*0xFFFFFFFF) | 0;
this.maskBytes.writeUInt32BE(maskKey, 0, true);
```

Bringing to an integer in this way now causes an error. When you replace with parseInt() it works correctly, but it will probably affect the speed?

(Google Translate)

**Comment by theturtle32** [comment]
This should have been fixed by the v1.0.26 release I just published.
