### ISSUE TITLE
Not building under OSX (10.11.6 - El Capitan)

### ISSUE THREAD

**Issue by cryptoeraser** [theturtle32/WebSocket-Node#333]
I am typing
`npm install ws --save`

and all hell breaks loose.

```
make: *** [Release/obj.target/validation/src/validation.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/me/dev/trading-dev/simple-websockets-setup/node_modules/utf-8-validate
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! no
```

**Comment by ibc** [comment]
You may want to report such an issue to the corresponding `ws` project (which is not this one).

**Comment by cryptoeraser** [comment]
Sure. Sorry. Funny how they just implemented this.
https://twitter.com/github/status/1057678791764467712?s=21
