### ISSUE TITLE
Error in sendUTF-function

### ISSUE THREAD

**Issue by christianhauff** [theturtle32/WebSocket-Node#335]
I have a completely new installation of node and installed websocket via npm. I have the [Server Example](https://www.npmjs.com/package/websocket#server-example) running and use my Firefox to execute the following lines:

```js
var connection = new WebSocket('ws://myserver.de:8080/', 'echo-protocol');
connection.send("hello world");
```

what appears on the server side is

```
user@server:~/tmp/websocket-server$ node websocket.js
Sun Nov 11 2018 11:44:18 GMT+0100 (CET) Server is listening on port 8080
Sun Nov 11 2018 11:44:26 GMT+0100 (CET) Connection accepted.
Received Message: hello world
/home/user/tmp/websocket-server/node_modules/websocket/lib/WebSocketConnection.js:730
    data = bufferFromString(data.toString(), 'utf8');
           ^

TypeError: utf8 is not a function
    at Function.from (native)
    at from (native)
    at WebSocketConnection.sendUTF (/home/user/tmp/websocket-server/node_modules/websocket/lib/WebSocketConnection.js:730:12)
    at WebSocketConnection.<anonymous> (/home/user/tmp/websocket-server/websocket.js:43:24)
    at emitOne (events.js:77:13)
    at WebSocketConnection.emit (events.js:169:7)
    at WebSocketConnection.processFrame (/home/user/tmp/websocket-server/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /home/user/tmp/websocket-server/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

Am I doing anything wrong? Anyone know where this error may come from? I am quite new to node.js, so it's hard for me to investigate further...

**Comment by vasilescur** [comment]
I'm having a similar issue. Make sure node is up to date, make sure all your packages are up to date (`npm install`, `npm rebuild`).

**Comment by ibc** [comment]
Let's close this issue.
