### ISSUE TITLE
Facing issue while running npm test in arm64 platform

### ISSUE THREAD

**Issue by ossdev07** [theturtle32/WebSocket-Node#336]
Working on arm64 platform and trying to test websocket test cases with npm test.
**Facing below error while testing the cases:**
> websocket@1.0.27 test /WebSocket-Node
> faucet test/unit

✓ Drop TCP Connection Before server accepts the request
⨯ Issue 195 - passing number to connection.send() shouldn't throw
  not ok 6 Unable to start echo server: Error: Echo Server exited unexpectedly with code 1
    ---
      operator: fail
      at: <anonymous> (/WebSocket-Node/test/unit/regressions.js:9:25)
      stack: |-
        Error: Unable to start echo server: Error: Echo Server exited unexpectedly with code 1
            at Test.assert [as _assert] (/WebSocket-Node/node_modules/tape/lib/test.js:224:54)
            at Test.bound [as _assert] (/WebSocket-Node/node_modules/tape/lib/test.js:76:32)
            at Test.fail (/WebSocket-Node/node_modules/tape/lib/test.js:317:10)
            at Test.bound [as fail] (/WebSocket-Node/node_modules/tape/lib/test.js:76:32)
            at /WebSocket-Node/test/unit/regressions.js:9:25
            at ChildProcess.<anonymous> (/WebSocket-Node/test/shared/start-echo-server.js:46:7)
            at ChildProcess.emit (events.js:182:13)
            at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
    ...
not ok 7 no plan found
⨯ fail  2
npm ERR! Test failed.  See above for more details.

Please guide me on testing this packages successfully in arm platform.
Thanks in advance.

**Comment by ibc** [comment]
Tests are supposed to be run on controlled environments. No need for them to run in any host.
