### ISSUE TITLE
Non-native version of example code fails with Chromium 22

### ISSUE THREAD

**Issue by phihag** [theturtle32/WebSocket-Node#76]
Using Chromium 22.0.1229.94 on debian sid (amd64) and node 0.9.0-pre, I cannot get the [example code](https://gist.github.com/raw/4508980/1c88dcbeb494a666975e7187dfe0e4889b19439f/wse.js) to work. When I enter

```
new WebSocket('ws://127.0.0.1:8080/')
```

in the chrome developer console, WebSocket crashes:

```
$ node wse.js 
Warning: Native modules not compiled.  XOR performance will be degraded.
Warning: Native modules not compiled.  UTF-8 validation disabled.
Fri Jan 11 2013 09:35:38 GMT+0100 (CET) Server is listening on port 8080

/home/phihag/scratch/websockets/node_modules/websocket/lib/WebSocketRequest.js:288
            throw new Error("Specified protocol was not requested by the clien
                  ^
Error: Specified protocol was not requested by the client.
    at WebSocketRequest.accept (/home/phihag/scratch/websockets/node_modules/websocket/lib/WebSocketRequest.js:288:19)
    at WebSocketServer.<anonymous> (/home/phihag/scratch/websockets/wse.js:37:30)
    at WebSocketServer.EventEmitter.emit (events.js:115:20)
    at WebSocketServer.handleUpgrade (/home/phihag/scratch/websockets/node_modules/websocket/lib/WebSocketServer.js:189:14)
    at Server.EventEmitter.emit (events.js:115:20)
    at Socket.socket.ondata (http.js:1702:14)
    at TCP.onread (net.js:404:27)
```

**Comment by imvikaskohli** [comment]
@theturtle32 Tx man you saved so much time of ours
